name: CI

on:
  push:
    branches:
      - '**' # Ignores pushes of tags
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: DbUp/Universe/.github/workflows/build.yml@main
